export const destinations = [
  {
    id: "about",
    name: "The kampung",
    category: "01 / MY STORY",
    color: "#e9a16d",
    angle: -0.9,
    title: "Hi, I’m Izzat.",
    subtitle: "An engineer. A builder. A little curious.",
    text: "I’m a Senior Frontend Engineer based in Kuala Lumpur, Malaysia. I build frontend platforms, design systems, and web apps that teams can maintain. My journey started in Mechanical & Manufacturing Engineering at the University of New South Wales, graduating in 2018, before taking me through technical support, project engineering, and software.",
    facts: [
      "Kuala Lumpur, Malaysia",
      "UNSW · Engineering, 2018",
      "English & Malay",
    ],
    href: "/#experience",
    link: "More about my journey",
  },
  {
    id: "work",
    name: "The workshop",
    category: "02 / SELECTED WORK",
    color: "#9bb8eb",
    angle: 0.4,
    title: "Built for the real world.",
    subtitle: "From shared platforms to independent products.",
    text: "At Xsolla, I lead the Business Accounts platform SDK used by approximately 25 account apps: shared packages, Module Federation, developer tooling, analytics, and observability. My independent builds include Kiddoly, a caregiving app; SimpleResume, a privacy-first resume builder; and SettleHere, a Malaysia home planner.",
    facts: [
      "Xsolla Business Accounts",
      "Cross-platform design systems",
      "Kiddoly · SimpleResume · SettleHere",
    ],
    href: "/#projects",
    link: "Explore the projects",
  },
  {
    id: "skills",
    name: "The observatory",
    category: "03 / MY TOOLBOX",
    color: "#c1ace8",
    angle: 1.65,
    title: "Good tools. Thoughtful systems.",
    subtitle: "The craft behind the things I build.",
    text: "React, TypeScript, Next.js, and React Native are at the heart of my work. Beyond interfaces, I work on monorepos, reusable packages, release workflows, CLI tooling, MCP servers, and production observability. I care about systems that make the next engineer’s work easier.",
    facts: [
      "React · TypeScript · Next.js",
      "React Native · Expo",
      "Platform architecture & developer tooling",
    ],
    href: "/#skills",
    link: "See the full toolbox",
  },
  {
    id: "writing",
    name: "The reading nook",
    category: "04 / FIELD NOTES",
    color: "#e5c676",
    angle: 2.85,
    title: "Notes from the workbench.",
    subtitle: "Things learned by building and shipping.",
    text: "I write about frontend architecture, shared platforms, and design systems. Read about building one design system across products, moving from application skeletons to a shared Accounts SDK, and helping AI agents work with platform conventions.",
    facts: [
      "One design system, every product",
      "From skeleton to Accounts SDK",
      "Stop AI-syncing the starter",
    ],
    href: "/blog",
    link: "Read the field notes",
  },
  {
    id: "contact",
    name: "Kopi & a chat",
    category: "05 / SAY HELLO",
    color: "#e69aab",
    angle: 4.05,
    title: "Something in mind?",
    subtitle: "Good things often start with a conversation.",
    text: "Have a web app, platform, or design system to ship? I’m available for freelance and consulting work. Send me the current workflow, product idea, or engineering problem, and I’ll help shape it into a clear build plan.",
    facts: [
      "Freelance & consulting",
      "Frontend platforms & web apps",
      "Based in Kuala Lumpur",
    ],
    href: "mailto:izzat.online@gmail.com",
    link: "Let’s talk over email",
  },
] as const;
export type Destination = (typeof destinations)[number];

export const POND_INDEX = destinations.length;
